name: pdk_workflow
run-name: ${{ github.actor }} pdk_workflow

on:
  - push
  - pull_request

jobs:
  pdk:
    name: pdk
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: validate
        uses: devops-jason/action-pdk@main
        with:
          action: 'validate'

      - name: unit tests
        uses: devops-jason/action-pdk@main
        with:
          action: 'test unit'